/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/{user_id}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Tapestry Memories */
        get: operations["list_user_tapestry_memories_users__user_id__memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Threads
         * @description Get threads for a user.
         *
         *     The thread payload is formatted as an [Activity Streams 2.0](https://www.w3.org/TR/activitystreams-core/) compliant object.
         *     Extension field: Some nodes may include `fibreKind` next to type. While type remains the canonical AS2 type,
         *     fibreKind further distinguishes our domain-specific interaction kinds (e.g., to disambiguate multiple product interactions that would otherwise share the same AS2 type).
         *     This field is optional, non-standard, and safe to ignore for generic AS2 clients. We intend to publish a formal AS2 extension for these semantics.
         *
         *     > [!NOTE]
         *     > If the response contains no threads, it could mean one of the following:
         *     >
         *     > - **Consent not completed**: The user hasn't completed a consent flow with any provider yet.
         *     >   You should either prompt the user for consent again or wait for the consent to complete.
         *     >   When it does, Fabric will send a callback to the URL you configured in your consent config,
         *     >   confirming the consent succeeded.
         *     > - **Data not yet available**: The user has completed the consent, but the data is still being
         *     >   processed on Fabric's side. You should keep polling this endpoint until threads become available.
         *     > - **Processing error**: There was an error during the consent flow or while processing the data
         *     >   on Fabric's side. Please contact Fabric support for assistance.
         *
         *     > [!TIP]
         *     > If a thread has `is_asset` set to `true`, you can obtain a signed URL for the asset
         *     > by calling the [`/users/{user_id}/threads/{thread_id}/asset`](#tag/users/GET/users/{user_id}/threads/{thread_id}/asset) endpoint.
         */
        get: operations["list_user_threads_users__user_id__threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListMemoriesResponse */
        ListMemoriesResponse: {
            /** Items */
            items: components["schemas"]["TapestryMemoryItem"][];
            /**
             * Next Page Token
             * @description An opaque token to pass as `page_token` query parameter to retrieve the next page of results. `null` when there are no more results.
             */
            next_page_token?: string | null;
            /**
             * Has More
             * @description Whether there are more results available beyond this page. Keep paginating with `next_page_token` until this is `false`.
             */
            has_more: boolean;
        };
        /**
         * PageSortDirection
         * @description Enumeration for sorting direction.
         * @enum {string}
         */
        PageSortDirection: PageSortDirection;
        /** PaginationResponse[UserThreadSchema] */
        PaginationResponse_UserThreadSchema_: {
            /** Items */
            items: components["schemas"]["UserThreadSchema"][];
            /**
             * Next Page Token
             * @description An opaque token to pass as `page_token` query parameter to retrieve the next page of results. `null` when there are no more results.
             */
            next_page_token?: string | null;
            /**
             * Has More
             * @description Whether there are more results available beyond this page. Keep paginating with `next_page_token` until this is `false`.
             */
            has_more: boolean;
        };
        /** TapestryMemoryItem */
        TapestryMemoryItem: {
            /**
             * Id
             * @description The unique identifier of the memory
             */
            id: string;
            /**
             * Content
             * @description The memory content
             */
            content: string;
            /**
             * From Date
             * @description Start of the period this memory covers
             */
            from_date?: string | null;
            /**
             * To Date
             * @description End of the period this memory covers
             */
            to_date?: string | null;
            /**
             * Similarity
             * @description Cosine similarity score (0–1), only present when a query is given
             */
            similarity?: number | null;
        };
        /** UserThreadSchema */
        UserThreadSchema: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Interaction Type */
            interaction_type?: string | null;
            /** Preview */
            preview?: string | null;
            /**
             * Payload
             * @description The thread data formatted as an [ActivityStreams 2.0](https://www.w3.org/TR/activitystreams-core/) compliant object.
             */
            payload: {
                [key: string]: unknown;
            };
            /** Version */
            version: string;
            /** Asat */
            asat?: string | null;
            /**
             * Is Asset
             * @default false
             */
            is_asset: boolean;
            /** Asset Description */
            asset_description?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaListMemoriesResponse = components['schemas']['ListMemoriesResponse'];
export type SchemaPaginationResponseUserThreadSchema = components['schemas']['PaginationResponse_UserThreadSchema_'];
export type SchemaTapestryMemoryItem = components['schemas']['TapestryMemoryItem'];
export type SchemaUserThreadSchema = components['schemas']['UserThreadSchema'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    list_user_tapestry_memories_users__user_id__memories_get: {
        parameters: {
            query?: {
                query?: string | null;
                from_date?: string | null;
                to_date?: string | null;
                page_token?: string | null;
                page_size?: number;
                direction?: components["schemas"]["PageSortDirection"] | null;
            };
            header?: {
                /** @description The api key generated from the Fabric developer portal */
                "x-api-key"?: string;
            };
            path: {
                /** @description The ID of the user */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMemoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_threads_users__user_id__threads_get: {
        parameters: {
            query?: {
                /** @description Filter by interaction type. See GET /interaction-types for valid values. */
                interaction_type?: string | null;
                /** @description Only return threads from this date onwards */
                from_date?: string | null;
                /** @description Only return threads until this date */
                to_date?: string | null;
                page_token?: string | null;
                page_size?: number;
                direction?: components["schemas"]["PageSortDirection"] | null;
            };
            header?: {
                /** @description The api key generated from the Fabric developer portal */
                "x-api-key"?: string;
            };
            path: {
                /** @description The ID of the user */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginationResponse_UserThreadSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
export enum PageSortDirection {
    asc = "asc",
    desc = "desc"
}
